<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <base href="../../">
    <link rel="stylesheet" href="assets/css/main.css">
    <title>Layout template</title>
  </head>
  <body>
    <nav class="navbar container">
      <a href="#" class="navbar-brand">
        <img class="img-fluid logo zoomin" src="assets/images/logo-2.png" alt="Logo" title="Logo">
        <h3 class="h3-fluid">Inicio</h3>
      </a>
      <div class="container">
        <form class="" action="#" method="get">
          <div class="row">
            <div class="col-8">
              <input type="text" name="search" value="" placeholder="">
            </div>
            <div class="col-4">
              <button class="btn" type="submit" alt="Buscar" title="Buscar">Buscar</button>
            </div>
          </div>
        </form>
      </div>
    </nav>

    <!-- notification area -->
    <hr>
    <div class="container news">
      <div class="row">
        <div class="col-4">
          <h2> El Hospital </h2>
          <h4> Este centro de salud tiene un programa de residencias de primer nivel en el pais. Se ofrecen oportunidades de práctica intensiva y supervisada en ambitos profesionales y por la misma -por supuesto- se recibe un salario mensual, acorde a lo que la regulación médica profesional lo indica en cada momento. </h4>
          <button class="btn" type="submit" alt="Más Información" title="Más Información">Más info > > </button>
        </div>
        <div class="col-4">
          <h2> Guardia </h2>
          <h4> Hospital Dr. Ricardo Guitierrez de La Plata dispone de un sofisticado servicio de guardias medicas las 24 horas para la atención de distintas urgencias. La administración de la institución hace viable una eficiente superación de los pacientes según el nivel de seriedad y tipo de patología. </h4>
          <button class="btn" type="submit" alt="Más Información" title="Más Información">Más info > > </button>
        </div>
        <div class="col-4">
          <h2> Especialidades </h2>
          <h4> Acorde a una respetable trayectoria en materia de medicina y salud, en Hospital Dr. Ricardo Gutierrez de La Plata podemos encontrar profesionales de salud. Del mismo modo, se brinda atención programada y de urguencias, se realizan estudios médicos y se brinda soporte en muchas de las ramas comunes de la medicina moderna. </h4>
          <button class="btn" type="submit" alt="Más Información" title="Más Información">Más info > > </button>
        </div>
      </div>
    </div>

    <!-- footer -->

    <footer>
      <div class="float-left">
        <p>&copy; 2017 - Hospital de Niños Ricardo Gutierrez.</p>
      </div>
      <div class="float-right">
        <p>v0.1.0</p>
      </div>
    </footer>
  </body>
</html>
