<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <base href="../../">
    <link rel="stylesheet" href="assets/css/main.css">
    <link rel="stylesheet" href="assets/css/login.css">
    <title>Layout template</title>
  </head>
  <body>
    <nav class="navbar container">
      <a href="#" class="navbar-brand">
        <img class="img-fluid logo zoomin" src="assets/images/logo-2.png" alt="Logo" title="Logo">
        <h3 class="h3-fluid">Inicio</h3>
      </a>
      <div class="">
        <form class="" action="#" method="get">
          <div class="row">
            <div class="col-8">
              <input type="text" name="search" value="" placeholder="">
            </div>
            <div class="col-4">
              <button class="btn" type="submit">Search</button>
            </div>
          </div>
        </form>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class "col-12">
          <form action="/action_page.php">
            Usuario:<br>
            <input type="text" name="username" value="" required>
            <br>
            Contraseña:<br>
            <input type="password" name="password" value="" required>
            <br><br>
            <button class="btn" type="submit" alt="Aceptar">Aceptar</button>
          </form>
        </div>
      </div>
    </div>

    <footer>
      <div class="float-left">
        <p>&copy; 2017 - Hospital de Niños Ricardo Gutierrez.</p>
      </div>
      <div class="float-right">
        <p>v0.1.0</p>
      </div>
    </footer>
  </body>
</html>
