<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <base href="../../">
    <link rel="stylesheet" href="assets/css/main.css">
    <title>Layout template</title>
  </head>
  <body>
    <nav class="navbar container">
      <a href="#" class="navbar-brand">
        <img class="img-fluid logo" src="" alt="Logo" title="Logo">
        <h3 class="h3-fluid">Inicio</h3>
      </a>
      <div class="">
        <form class="" action="#" method="get">
          <div class="row">
            <div class="col-8">
              <input type="text" name="search" value="" placeholder="">
            </div>
            <div class="col-4">
              <button class="btn" type="submit">Search</button>
            </div>
          </div>
        </form>
      </div>
    </nav>

    <!--  -->

    <footer>
      <div class="float-left">
        <p>&copy; 2017 - Hospital de Niños Ricardo Gutierrez.</p>
      </div>
      <div class="float-right">
        <p>v0.1.0</p>
      </div>
    </footer>
  </body>
</html>
